{% set name = "oauth2client" %}
{% set version = "4.1.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "d486741e451287f69568a4d26d70d9acd73a2bbfa275746c535b4209891cccc6" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - httplib2 >=0.9.1
    - pyasn1 >=0.1.7
    - pyasn1-modules >=0.0.5
    - rsa >=3.1.4
    - six >=1.6.1

test:
  imports:
    - oauth2client
    - oauth2client.contrib

about:
  home: https://github.com/google/oauth2client/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'OAuth 2.0 client library'
  dev_url: https://github.com/google/oauth2client/
  doc_url: https://oauth2client.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
